---
title: "Forecaset Euribor"
author: "Caio Moreno de Souza"
date: "October 17, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is a quick forecast of Euribor. Please do not use it. Only a dirty prediction.

```{r}




#euribor <- read.csv("C:\\Users\\cmoreno\\Desktop\\Euribor\\euribor\\data\\euribor-12m-monthly.csv", sep=",", header = TRUE)

# Read Euribor Dataset from Github
euribor <- read.csv("https://raw.githubusercontent.com/caiomsouza/forecast-euribor/master/euribor/data/euribor-12m-monthly.csv", sep=",", header = TRUE)


euribor

euribor.df <- as.data.frame(euribor)

# Remove columns maturity_level and granularity
euribor.df <- euribor.df[, setdiff(names(euribor.df), c("maturity_level", "granularity"))]
euribor.df


plot(euribor.df)

#install.packages("ggplot2")
#library(ggplot2)

#install.packages("prophet")
#library(prophet)

#install.packages("Rcpp")
#library("Rcpp")

#install.packages("forecast")
library(forecast)


#https://research.fb.com/prophet-forecasting-at-scale/


# https://cran.r-project.org/web/packages/forecast/forecast.pdf


ts = ts(euribor.df)
ts
plot(ts[,2])
plot(ts[,2],type="o",col="blue") 


ts[,1]
ts[,2]

ts

# Predict using Auto Arima
fit <- auto.arima(ts[,2])
plot(forecast(fit,h=20))

# 30 years x 12 months = 360 months
# Predict using Auto Arima for 120 months
fit <- auto.arima(ts[,2])
plot(forecast(fit,h=360))
fit
fit$residuals
fit$fitted
fit$x


# Predict using Auto Arima for 120 months
fit <- auto.arima(ts[,2])
plot(forecast(fit,h=120))

# Predict using Auto Arima for 3 months
fit <- auto.arima(ts[,2])
plot(forecast(fit,h=3))


# Predict using Auto Arima for 48 months
fit <- auto.arima(ts[,2])
plot(forecast(fit,h=48))

# Predict using Auto Arima for 12 months
fit <- auto.arima(ts[,2])
plot(forecast(fit,h=12))

# Predict using Auto Arima for 6 months
fit <- auto.arima(ts[,2])
plot(forecast(fit,h=6))

# Predict using Auto Arima for 6 months
fit <- auto.arima(ts[,2])
plot(forecast(fit,h=6))

#12 months x 10 years = 120 months





```


If you want to contribute to improve it, please contact me.

Questions:

How is it possible to predict Euribor for 20 to 40 years?

What is the magic? 

